name: singularityenv
channels:
    - conda-forge
    - bioconda
dependencies:
    - python>3.11
    - snakemake
    - pandas
    - pyyaml
    - numpy
    - regex
    - cellsnp-lite
    - pip           # <- must be listed as a conda dependency
    - pip:          # <- pip installations under second pip heading
        - vireoSNP
